console.log("girar a la izquierda")
console.log("avanzar")
console.log("girar a la derecha")
console.log("avanzar")
console.log("avanzar")
console.log("girar a la derecha")
console.log("avanzar")
console.log("vaciar 1")
