//LE INFORMAMOS AL USUARIO LO QUE HACE EL PROGRAMA//
console.log("GRACIAS POR UTILIZAR ESTE PROGRAMA, EL CUAL IDENTIFICARA SI SU NUMERO ES PAR O IMPAR")

//IMPORTAMOS RLS//
import * as readlinsync from 'readline-sync'

//LE PEDIMOS AL USUARIO QUE INGRESE SU NUMERO//
console.log("INGRESE SU NUMERO Y PRESIONE LA TECLA ENTER")
let number : number = readlinsync.questionFloat()

//LE DEVOLVEMOS EL NRO AL USUARIO//
console.log("EL NUMERO INGRESADO FUE: " + number)

//SI EL NUMERO INGRESADO ES 0, SE LO DECIMOS. SINO, SI EL NUMERO ES DIVISIBLE POR 2 Y SU RESTO ES 0, INFORMAMOS QUE ES PAR, Y SINO EL NRO ES IMPAR//
if (number==0){
    console.log("SU NUMERO ES 0, LO CUAL NO ES PAR NI TAMPOCO IMPAR ")
} else if ( 0==number%2 ) {
console.log("SU NUMERO ES PAR")
} else 
    console.log("SU NUMERO ES IMPAR")
